from . import trial
from . import channels
from . import read
from . import sig_proc
from . import plot
from . import types
from . import demo
from .trial import TrialInfo
from .trial import Trial
from .demo import test_install
from .demo import tutorial_data
from .trial import load
